ALTER TABLE subject_configs
  ADD COLUMN IF NOT EXISTS micro_count_again INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS micro_count_hard  INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS micro_count_good  INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS micro_count_easy  INTEGER NOT NULL DEFAULT 0;
