import { Router } from 'express';
import evaluateRouter from './evaluate.js';
import decisionRouter from './decision.js';
import transcribeRouter from './transcribe.js';
import lookupRouter from './lookup.js';
import socraticRouter from './socratic.js';
import statsRouter from './stats.js';
import overviewRouter from './overview.js';
import schedulerRouter from './scheduler.js';
import activityRouter from './activity.js';
import curriculumRouter from './curriculum.js';
import advisorRouter from './advisor.js';
import sessionPlannerRouter from './session-planner.js';
import sqlValidateRouter from './sql-validate.js';
import cardsRouter from './cards.js';
import promptToolsRouter from './prompt-tools.js';
import studyDoubtRouter from './study-doubt.js';
import studySessionsRouter from './study-sessions.js';
import githubImportRouter from './github-import.js';

const router = Router();

router.use(cardsRouter);
router.use(promptToolsRouter);
router.use(studyDoubtRouter);
router.use(studySessionsRouter);
router.use(githubImportRouter);
router.use(evaluateRouter);
router.use(decisionRouter);
router.use(transcribeRouter);
router.use(lookupRouter);
router.use(socraticRouter);
router.use(statsRouter);
router.use(overviewRouter);
router.use(schedulerRouter);
router.use(activityRouter);
router.use(curriculumRouter);
router.use(advisorRouter);
router.use(sessionPlannerRouter);
router.use(sqlValidateRouter);

export default router;
